# fly.toml app configuration file for spellcheck-poc
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spellcheck-poc'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'python -c "import main; print(\"App configuration validated\")"'

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'

[[mounts]]
  source = "spellcheck_data"
  destination = "/data"